config/routes.rb
Rails.application.routes.draw do
  
# トップページ
  root 'static_pages#top'
  get  '/signup', to:'users#new'
  get  '/edit-attendance-system', to:'attendances#edit_attendance_system'
  
# ログインのルーティング
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/login', to: 'sessions#destroy'

# 拠点のルーティング
  resources :offices

# ユーザーに紐づける
  resources :users do
    member do
      # ユーザー基本情報
      get   'edit_basic_info'
      patch 'update_basic_info'
      
      # 勤怠情報編集
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'approval_show'
      get   'attendances/approval_log'
    end

    # 勤怠情報編集確認
    get   'approval_edit_month'
    patch 'update_approval_edit_month'

    # 残業申請確認
    get   'approval_overtime_request'
    patch 'update_approval_overtime_request'
    
    # 1ヶ月の申請確認
    get   'approval_one_month'
    patch 'update_approval_one_month'
    
    get   'approval_month_report'
    patch 'update_approval_month_report'
    
    get   'employee_index'
    
    # 勤怠情報に紐付ける
    resources :attendances, only: [:update, :edit] do
      member do
        # 残業申請依頼
        get   'overtime_request'
        patch 'update_overtime_request'
      end
    end
    
    resources :reports, only: :update
    
    # ユーザー情報をCSVからインポート
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/office.rb
class Office < ApplicationRecord
  has_many :users, dependent: :destroy
  
  validates :office_name, presence: true, length: { in: 2..30 }, uniqueness: true  
  
  enum office_type: { 出勤: "出勤", 退勤: "退勤" }
  # validate :name_only_once
  # validate :number_only_once
  
  # def name_only_once
  #   errors.add(:office_name, "は登録済です") if started_at.blank? && finished_at.present?
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office,     only: [:edit, :destroy, :update]
  before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update, :index]
  before_action :admin_user,     only: [:new, :create, :destroy, :edit, :update, :index]
  
  def new
    @office = Office.new
  end
  
  def index
    @offices = Office.all
  end
  
  def edit
  end
  
  def create
    @office = Office.new(offices_params) #officeモデルの新しいパラメーターを＠officeに代入
    if @office.save#  @officeの登録に成功したら
      if @office.office_type == "出勤"
        @office.office_number = @office.id + 100
        @office.save
      elsif @office.office_type == "退勤"
        @office.office_number = @office.id + 200
        @office.save
      end
      flash[:success] = '拠点登録に成功しました。' # 成功メッセージを出す
      redirect_to offices_url
    else
      render :new # 失敗したらnewに戻る
    end
  end
  
  def edit
  end
  
  def destroy
    @office.destroy
    flash[:success] = "#{@office.office_name}を削除しました。"
    redirect_to offices_url
  end
  
  def update
    if @office.update_attributes(offices_params)
      if @office.office_type == "出勤"
        @office.office_number = @office.id + 100
        @office.save
      elsif @office.office_type == "退勤"
        @office.office_number = @office.id + 200
        @office.save
      end
      flash[:success] = "更新成功"

      redirect_to offices_url
    else
      render :index
    end
  end
  
  private
  
    def offices_params # ストロングパラメーター　officeのパラメーターは
      # requireメソッドでオブジェクト名を定める。permitでキーを指定する。
      params.require(:office).permit(:office_name, :office_number, :office_type)
    end
    
    def mk_number
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_error_messages.html.erb
<% if object.errors.any? %>

  <div id="error_explanation">
    <div class="alert alert-danger">
      入力エラーが<%= object.errors.count %>件ありました。
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/offices/edit.html.erb
<% provide(:title, "OfficeEdit") %>
<h1>拠点編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  　
    <%= form_with(model: @office, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    
      <%= f.label :office_name, class: "label-offices" %>
      <%= f.text_field :office_name, class: "form-control" %>

      <%= f.label :office_type, class: "label-offices" %>
      <%= f.select :office_type, Office.office_types.keys.map {|k| [k, k]}, {}, { class: 'form-control', style: 'margin-bottom: 5px;', data: {} } %>
      
      <%= f.submit "登録", class: "btn btn-primary btn-block btn-offices" %>
    <% end %>
  </div>
</div>

app/views/offices/index.html.erb
<% provide(:title, "All offices")%>
<h1>拠点一覧</h1>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-offices">
    <thead>
      
        <tr>
          <td></td>
          <td></td>
          <td>拠点番号</td>
          <td>拠点名</td>
          <td>勤怠種類</td>
        </tr>
      
    </thead>
    
    <% @offices.each do |office| %>
    <tr>
      <td><%= link_to "修正", edit_office_path(office), class: "btn btn-primary" %></td>
      <td>
          <%= link_to "削除", office, method: :delete,
              data: { confirm: "#{office.office_name}を削除してよろしいですか？" },
              class: "btn btn-primary" %>
      </td>
      <td><%= office.office_number%></td>
      <td><%= office.office_name%></td>
      <td><%= office.office_type%></td>
    </tr>
    <% end %>
  </table>
</div>

<div class="jumbotron">
  <%= link_to "拠点情報追加", new_office_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/offices/new.html.erb
<% provide(:title, "OfficeSignup") %>
<h1>拠点登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  　
    <%= form_with(model: @office, local: true) do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    
      <%= f.label :office_name, class: "label-offices" %>
      <%= f.text_field :office_name, class: "form-control" %>
      
      <%= f.label :office_number, class: "label-offices" %>
      <%= f.text_field :office_number, class: "form-control" %>
      
      <%= f.label :office_type, class: "label-offices" %>
      <%= f.select :office_type, Office.office_types.keys.map {|k| [k, k]}, {}, { class: 'form-control', style: 'margin-bottom: 5px;', data: {} } %>
      
      <%= f.submit "登録", class: "btn btn-primary btn-block btn-offices" %>
    <% end %>
  </div>
</div>