config/routes.rb
Rails.application.routes.draw do
  
# トップページ
  root 'static_pages#top'
  get  '/signup', to:'users#new'
  get  '/edit-attendance-system', to:'attendances#edit_attendance_system'
  
# ログインのルーティング
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/login', to: 'sessions#destroy'

# 拠点のルーティング
  resources :offices

# ユーザーに紐づける
  resources :users do
    member do
      # ユーザー基本情報
      get   'edit_basic_info'
      patch 'update_basic_info'
      
      # 勤怠情報編集
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'approval_show'
      get   'attendances/approval_log'
    end

    # 勤怠情報編集確認
    get   'approval_edit_month'
    patch 'update_approval_edit_month'

    # 残業申請確認
    get   'approval_overtime_request'
    patch 'update_approval_overtime_request'
    
    # 1ヶ月の申請確認
    get   'approval_one_month'
    patch 'update_approval_one_month'
    
    get   'approval_month_report'
    patch 'update_approval_month_report'
    
    get   'employee_index'
    
    # 勤怠情報に紐付ける
    resources :attendances, only: [:update, :edit] do
      member do
        # 残業申請依頼
        get   'overtime_request'
        patch 'update_overtime_request'
      end
    end
    
    resources :reports, only: :update
    
    # ユーザー情報をCSVからインポート
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :reports, dependent: :destroy
  belongs_to :office
  #remember_tokenという仮想属性を作成
  attr_accessor :remember_token
  # 現在のメールアドレス(self.email)の値をdowncaseで小文字に変換
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: { maximum: 100 },
  #                   format: { with: VALID_EMAIL_REGEX },
  #                   uniqueness: true  
  validates :email, format: {with: VALID_EMAIL_REGEX}, allow_blank: true
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true 
  validates :employee_number, uniqueness: true
  validates :uid, uniqueness: true
  validates :basic_work_time, presence: true, allow_nil: true
  validates :designated_work_end_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true #ブランクをスルー
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true # nilをスルー


  def self.import(file)
    num = 0
    CSV.foreach(file.path, headers: true,) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      
      # 保存する
      user.save!
      num += 1
    end
    num
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "email" , "office_id", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end


  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す.Rubyの標準ライブラリSecureRandomモジュールにあるurlsafe_base64
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返す
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search) #ここでのself.はUser.を意味する
    if search
      where(['name LIKE ?', "%#{search}%"]) #検索とnameの部分一致を表示。User.は省略
    else
      all #全て表示。User.は省略
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,       only: [:show, :edit, :update, :destroy, :approval_show]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :approval_show]
  before_action :correct_user,   only: [:show, :edit, :update, :destroy]
  before_action :admin_user,     only: [:destroy, :update, :index, :employee_index]
  before_action :set_one_month,  only: [:show, :approval_show]
  before_action :set_month,  only: :show
  
# ユーザーの勤怠画面へ遷移（するときの処理）
  def show
    @superiors = User.where(superior: true).where.not(id: @user.id).select(:name)
    @worked_sum = @attendances.where.not(started_at: nil).count
    @approval_edit_sum = Attendance.where(application_superior_name: @user.name, edit_status: "申請中").count
    @approval_overtime_sum = Attendance.where(overtime_application_superior_name: @user.name, overtime_status: "申請中").count
    @approval_onemonth_sum = Report.where(application_onemonth_superior_name: @user.name, approval_month_status: "申請中").count
# CSV出力
    respond_to do |format| 
      format.html 
      format.csv do
          send_data render_to_string, 
          filename: "#{@user.name}-#{@first_day.year}_#{@first_day.month}.csv", type: :csv #csv用の処理を書く
      end
    end
  end
  
# ユーザーの一覧ページへ画面遷移（するときの処理）
  def index
    @users = User.all.where.not(admin: true ).paginate(page: params[:page]).search(params[:search])
    @offices = Office.all
  end
  
  def employee_index
    # @attendances = Attendance.where(finished_at: nil).where.not(started_at: nil).order(:user_id)
    @users = User.includes(:attendances).references(:attendances).
    where('attendances.started_at IS NOT NULL').
    where('attendances.finished_at IS NULL')
  end
  
# CSVファイルインポート機能
  def import
    if params[:csv_file].blank?
      flash[:danger] = "インポート するCSVファイルを選択してください。"
      redirect_to users_url and return
    else
      num = User.import(params[:csv_file])  # fileはtmpに自動で一時保存される
      if num > 0
        flash[:success] = "#{num.to_s}件のユーザー情報を追加しました。"
        redirect_to users_url and return
      else
        flash[:danger] = "読み込みエラーが発生しました。"
        redirect_to users_url and return
      end
    end
  end
  
# ユーザー新規登録画面へ遷移（するときの処理）
  def new
    @user = User.new
  end
  
# ユーザー新規登録の保存処理
  def create
    @office = Office.find_by(params[:user][:office_id])
    @user = User.new(user_params) #フォームから送られて来た新しいパラメーターを＠userに代入
    if @user.save #  @userの登録に成功したら
      if @user.affiliation == "総務部"
        @user.uid = @office.office_number.to_s + "-" + (@user.id + 1000).to_s
        @user.employee_number = @user.uid
        @user.save
      elsif @user.affiliation == "事務部"
        @user.uid = @office.office_number.to_s + "-" + (@user.id + 2000).to_s
        @user.employee_number = @user.uid
        @user.save
      elsif @user.affiliation == "人事部"
        @user.uid = @office.office_number.to_s + "-" + (@user.id + 3000).to_s
        @user.employee_number = @user.uid
        @user.save
      elsif @user.affiliation == "窓際部"
        @user.uid = @office.office_number.to_s + "-" + (@user.id + 4000).to_s
        @user.employee_number = @user.uid
        @user.save
      end
    
      log_in @user #保存成功後、ログインする
      flash[:success] = '新規作成に成功しました。' # 成功メッセージを出す
      redirect_to @user # redirect_to user_url(@user)をシンプルに記述　＞showへ遷移
    else
      render :new # 失敗したらnewに戻る
    end
  end
  
# ユーザー情報の編集画面へ遷移（するときの処理）
  def edit
    @offices = Office.all
  end
  
# ユーザ情報の更新処理
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "更新成功"
      redirect_to users_url
    else
      render :edit
    end
  end
  
# ユーザー情報の削除処理
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

# 残業申請確認モーダルへ遷移（するときの処理）
  def approval_overtime_request
    # ログインしているユーザーを特定する。
    @user = User.find(params[:user_id])
    # Attendanceテーブルから特定された上長名がカラムにデータを持つ勤怠データを＠attendanceに代入する。
    @attendances = Attendance.where(overtime_application_superior_name: @user.name, overtime_status: "申請中").order(user_id: "ASC", worked_on: "ASC").group_by(&:user_id)
  end
  
  def update_approval_overtime_request
    ActiveRecord::Base.transaction do
      overtime_request_params.each do |id, item|
        if item[:overtime_confirmation] == "1"
          attendance = Attendance.find(id)
          if item[:overtime_status] == "なし"
            item[:overtime_finished_at] = attendance.log_overtime_finished_at
            item[:overtime_next_day] = attendance.log_overtime_next_day
            item[:overtime_status] = attendance.log_overtime_status
            item[:overtime_note] = attendance.log_overtime_note
            item[:overtime_confirmation] = attendance.log_overtime_confirmation
            item[:overtime_application_superior_name] = attendance.log_application_superior_name
            flash[:danger] = "残業申請を削除しました。"
          elsif item[:overtime_status] == "承認"
            item[:log_overtime_status] = item[:overtime_status]
            item[:log_overtime_finished_at] = attendance.overtime_finished_at
            item[:log_overtime_next_day] = attendance.overtime_next_day
            item[:log_overtime_note] = attendance.overtime_note
            item[:log_application_superior_name] = attendance.overtime_application_superior_name
            item[:overtime_confirmation] = "残業申請承認済"
            item[:log_overtime_confirmation] = item[:overtime_confirmation]
            flash[:success] = "残業申請を承認しました。"
          elsif item[:overtime_status] == "否認"
            item[:overtime_confirmation] = "残業申請否認"
            flash[:danger] = "残業申請は否認されました。"
          end
          attendance.update_attributes!(item)
        else
          item[:overtime_status] = nil
        end
      end
    end
    redirect_to user_url(params[:user_id])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to user_url(params[:user_id])
  end

  # 勤怠情報確認モーダルへ遷移（するときの処理）
  def approval_edit_month
    # ログインしているユーザーを特定する。
    @user = User.find(params[:user_id])
    # Attendanceテーブルから特定された上長名がカラムにデータを持つ勤怠データを＠attendanceに代入する。
    @attendances = Attendance.where(application_superior_name: @user.name, edit_status: "申請中").order(user_id: "ASC", worked_on: "ASC").group_by(&:user_id)
  end
  
  def update_approval_edit_month
    ActiveRecord::Base.transaction do
      edit_approval_params.each do |id, item| #実際に飛んでくるitemはモーダル内で変更が効くカラムのパラメーター
        if item[:edit_confirmation] == "1" # 変更check boxが選択されているなら。
          attendance = Attendance.find(id) # attendanceにAttendanceテーブルのIDを代入する
          # binding.pry
          if item[:edit_status] == "なし"
            # binding.pry
            if attendance.before_edit_status == "承認" || attendance.before_edit_status == "否認"
              item[:edit_status] = attendance.before_edit_status if attendance.before_edit_status == "承認"
              item[:edit_status] = attendance.log_edit_status if attendance.before_edit_status == "否認"
              attendance.started_at = attendance.before_started_at 
              attendance.finished_at = attendance.before_finished_at 
              attendance.edit_started_at = attendance.before_started_at
              attendance.edit_finished_at = attendance.before_finished_at
              attendance.edit_note = attendance.before_edit_note
              attendance.note = attendance.before_edit_note
              item[:edit_confirmation] = attendance.before_edit_confirmation if attendance.before_edit_status == "承認"
              item[:edit_confirmation] = attendance.log_edit_confirmation if attendance.before_edit_status == "否認"
              attendance.application_superior_name = attendance.before_application_superior_name
              flash[:danger] = "勤務変更を削除しまし。"
            else
              attendance.note = attendance.before_edit_note
              attendance.edit_started_at = nil 
              attendance.edit_finished_at = nil
              attendance.next_day = nil
              item[:edit_note] = nil
              item[:edit_status] = nil
              item[:edit_confirmation] = nil
              attendance.application_superior_name = nil
              flash[:danger] = "勤務変更を削除しました。"
            end
          elsif item[:edit_status] == "承認"
            attendance.log_started_at = attendance.before_started_at if attendance.before_started_at.blank?
            attendance.log_finished_at = attendance.before_finished_at if attendance.before_finished_at.blank?
            attendance.before_edit_status = item[:edit_status]
            attendance.log_edit_status = item[:edit_status] if attendance.log_edit_status.blank?
            attendance.before_started_at = attendance.started_at# まず勤怠ページの勤怠情報を変更前勤怠に代入する。
            attendance.before_finished_at = attendance.finished_at
            attendance.started_at = attendance.edit_started_at # 承認なら変更時間を勤怠時間に代入する。
            attendance.finished_at = attendance.edit_finished_at
            attendance.before_next_day = attendance.next_day
            attendance.next_day = item[:edit_next_day]
            item[:edit_approval_date] = Date.current
            item[:edit_confirmation] = "編集承認済"
            attendance.before_edit_confirmation = item[:edit_confirmation]
            attendance.log_edit_confirmation = item[:edit_confirmation]
            flash[:success] = "勤怠情報を承認しました。"
          elsif item[:edit_status] == "否認"
            attendance.before_edit_status = item[:edit_status]
            item[:edit_confirmation] = "勤怠編集 否認"
            attendance.before_edit_confirmation = item[:edit_confirmation]
            flash[:danger] = "勤怠情報を否認しました。"
          end
            attendance.update_attributes!(item)
        else
          item[:edit_status] = nil 
        end
      end
    end
    redirect_to user_url(params[:user_id])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"

app/helpers/users_helper.rb
module UsersHelper
    # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_approval_month_report.html.erb
<% provide(:title, @user.name) %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">勤務申請承認</h1>
    </div>
<!--@reportのフォーム-->
    <div class="modal-body">
      <%= form_with(model: @user, url: user_update_approval_month_report_path(@reports), local: true, method: :patch) do |f| %>
        <% @reports.each do |id, reports| %>
          <% user = User.find(id) %>
          <div>
            <h3 class><%= "【#{user.name}からの勤怠変更申請】"%></h3>
            <table class="table table-bordered table-condensed" id="table-attendances">
              <thead>
                <tr>
                  <td>月</td>
                  <td>指示者確認㊞</td>
                  <td>変更</td>
                  <td>勤怠を確認する</td>
                </tr>
              </thead>
              
              <tbody>
                <% reports.each do |report| %>
                  <%= f.fields_for "reports[]", report do |re| %>
                    <tr>
                      <td><%= "#{report.report_month.month} 月" %></td>
                      <td><%= re.select :approval_month_status, ["なし", "申請中", "承認", "否認"], {include_blank: ""}, class: "form-control" %></td>
                      <td><%= re.check_box :report_confirmation %></td>
                      <td><%= link_to "確認", approval_show_user_path(id: user.id), class: "btn btn-primary btn-attendance" %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <div class="center">
          <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/approval_one_month.html.erb
    <div class="modal-body">
      <%= form_with(model: @user, url: user_update_approval_edit_month_path(@attendances), local: true, method: :patch) do |f| %>
        <% @attendances.each do |id, attendances| %>
          <% user = User.find(id) %>
          <div>
            <h3 class><%= "【#{user.name}からの勤怠変更申請】"%></h3>
            <table class="table table-bordered table-condensed" id="table-attendances">
              <thead>
                <tr>
                  <td>月</td>
                  <td>指示者確認㊞</td>
                  <td>変更</td>
                  <td>勤怠を確認する</td>
                </tr>
              </thead>
              
              <tbody>
                <% attendances.each do |attendance| %>
                  <%= f.fields_for "attendances[]", attendance do |at| %>
                    <tr>
                      <td><%= l(attendance.worked_on, format: :month_names) %></td>
                      <td><%= at.select :edit_status, ["なし", "申請中", "承認", "否認"], {include_blank: ""}, class: "form-control" %></td>
                      <td><%= at.check_box :edit_confirmation %></td>
                      <td><%= link_to "確認", approval_show_user_path(id: user.id, date: attendance.worked_on.beginning_of_month), class: "btn btn-primary btn-attendance" %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
      <% end %>
      <div class="center">
        <%= f.submit "変更を保存する", class: "btn btn-lg btn-primary" %>
      </div>
      <% end %>
    </div>

app/views/users/show.html.erb
<% unless @user.admin? %>
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "⬅︎", user_path(date: @first_day.prev_month), class: "btn btn-default" %>
        <%= l(@first_day, format: :middle) %> 時間管理表
        <%= link_to "➡︎︎", user_path(date: @first_day.next_month), class: "btn btn-default" %>
      </td>
      
      <td>
        指定勤務開始時間:      <%= l(@user.designated_work_start_time, format: :time) %><br/>
        指定勤務終了時間:      <%= l(@user.designated_work_end_time, format: :time) %>
      </td>
      <td colspan="3">基本時間 <%= format_basic_info(@user.basic_work_time) %></td>
      <td>          初日:      <%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属：    <%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：    <%= @user.name %></td>
      <td colspan="2">カードID:   <%= @user.uid %></td>
      <td>出勤日数  <%= @worked_sum %>日</td>
      <td>締め:     <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!--上長へのお知らせ-->
<div> 
  <% if current_user.superior? %>
    <div class= "alert_msg">
      <div>【所属長承認申請のお知らせ】
        <% if @approval_onemonth_sum > 0 %>
          <%= link_to ": #{@approval_onemonth_sum}件の通知があります。", user_approval_month_report_path(@user), remote:true, class: "danger" %> 
        <% end %>
      </div>
      <div>【勤怠変更申請のお知らせ】
        <% if @approval_edit_sum > 0 %>
          <%= link_to ": #{@approval_edit_sum}件の通知があります。", user_approval_edit_month_path(@user), remote:true, class: "danger" %> 
        <% end %>
      </div>
      <div>【残業申請のお知らせ】
        <% if @approval_overtime_sum > 0 %>
          <%= link_to ": #{@approval_overtime_sum}件の通知があります。", user_approval_overtime_request_path(@user), remote:true, class: "danger" %> 
        <% end %></div>
    </div>
  <% end %>
</div>

<!--テーブル上ボタン群-->
<div>
  <tr>
    <td class="pull-left"><%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-md btn-primary btn-attendance"%>
                          <%= link_to "CSV出力", user_path(format: :csv), class: 'btn btn-primary' %></td>
    <td colspan="2">      <%= link_to "勤怠修正ログ（承認済み）", attendances_approval_log_user_path(@user, date: @first_day), class: "btn btn-md btn-primary btn-attendance"%></td>
  </tr>
</div>

<!--勤怠情報テーブル-->
<div>
  <table class="table table-bordered table-condensed" id="table-attendances" >
    <thead>
      <tr>
        <td rowspan="3">残業申請</td>
        <td rowspan="3">日付</td>
        <td rowspan="3">曜日</td>
        <td colspan="8">【実績】</td>
        <td colspan="5">所定外勤務</td>
      </tr>
      <tr>
        <td colspan="3">出社</td>
        <td colspan="3">退社</td>
        <td rowspan="2">在社時間</td>
        <td rowspan="2">備考</td>
        <td colspan="2">終了予定時間</td>
        <td rowspan="2">時間外時間</td>
        <td rowspan="2">業務処理内容</td>
        <td rowspan="2">指示者確認㊞</td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
      </tr>
    </thead>
    
    <tbody>
      <!--set_one_monthをdayに対して繰り返す-->
      <% @attendances.each do |day| %>
      <!--土日に色を付ける-->
      <% css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土' then 'text-primary'
          when '日' then 'text-danger'
          end
      %>      
        <tr>
          <td><%= link_to "残業申請", overtime_request_user_attendance_path(@user, day), remote:true, class: "btn btn-primary btn-attendance"%></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <!-- もし今日と、出勤日が同じ　　且つ　勤務開始時間がないなら-->
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
            <!--ヘルパーのworking_timesに引数next_dayを追加(workingtimesはst時間、fn時間、nxのcbを参照する)-->
              <%= @str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.next_day) %>
              <% @total_working_times = @total_working_times.to_f + @str_times.to_f %>
            <% end %>
          </td>
          <td class="text-field"><%= day.note %></td>
          <td><%= format_hour(day.overtime_finished_at) if day.overtime_finished_at.present? %></td>
          <td><%= format_min(day.overtime_finished_at) if day.overtime_finished_at.present? %></td>
          <td>
            <% if day.overtime_status.present? %>
              <%= (overtimes_1(day.overtime_finished_at.floor_to(15.minutes),day.overtime_next_day)) if day.overtime_finished_at.present? %>
            <% end %>
          </td>
          <td class="text-field"><%= day.overtime_note %></td>
          <td>
            <% if day.edit_status == "申請中" %>
              <%= "#{day.application_superior_name} へ勤務変更申請中" %></br>
            <% elsif (day.edit_status == "否認") || (day.edit_status == "承認") %>
              <%= "#{day.edit_confirmation} ：#{day.application_superior_name}" %></br>
            <% end %>
            <% if day.overtime_status == "申請中" %>
              <%= "#{day.overtime_application_superior_name} へ残業申請中" %></br>
            <% elsif (day.overtime_status == "否認") || (day.overtime_status == "承認") %>
              <%= "#{day.overtime_confirmation} ：#{day.overtime_application_superior_name}" %>
            <% elsif day.overtime_status == "なし" %></br>
              　<%=  %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <% %> 
      <div class ="form"
      <tr>
        <td rowspan="2"></td>
        <td colspan="2">累計日数</td>
        <td colspan="6">基本勤務時間</td>
        <td>在社時間合計</td>
        <td colspan="3"></td>
        <td></td>
        <td></td>
        <td rowspan="2">
          <ol>
            <% if @report.approval_month_status == "申請中"%>
              <li><%= "#{@report.application_onemonth_superior_name} へ勤怠承認申請中" %></li>
              <li>
                <%= form_with(model: @report, url: user_report_path(@user, @report), local: true, method: :patch) do |f| %>
                  <%= f.hidden_field :user_id, :value => @user.id %>
                  <%= f.hidden_field :approval_month_status, :value => "申請中" %>
                  <%= f.hidden_field :report_month, :value => @first_day %>
                  <%= f.collection_select :application_onemonth_superior_name, @superiors, :name, :name, {prompt: "選択してください"}, class: "form-control" %>
                  <%= f.submit "再申請 送信", class: "btn btn-block btn-primary" %>
                <% end %>
              </li>
            <% elsif (@report.approval_month_status == "承認") || (@report.approval_month_status == "否認") %>
              <li><%= "#{@report.application_onemonth_superior_name}により#{@report.report_confirmation}" %></li>
              <li>
                <%= form_with(model: @report, url: user_report_path(@user, @report), local: true, method: :patch) do |f| %>
                  <%= f.hidden_field :user_id, :value => @user.id %>
                  <%= f.hidden_field :approval_month_status, :value => "申請中" %>
                  <%= f.hidden_field :report_month, :value => @first_day %>
                  <%= f.collection_select :application_onemonth_superior_name, @superiors, :name, :name, {prompt: "選択してください"}, class: "form-control" %>
                  <%= f.submit "再申請 送信", class: "btn btn-block btn-primary" %>
                <% end %>
              </li>
            <% else %>
              <li>所属長承認 未</li>
              <li>
                <%= form_with(model: @report, url: user_report_path(@user, @report), local: true, method: :patch) do |f| %>
                  <%= f.hidden_field :user_id, :value => @user.id %>
                  <%= f.hidden_field :approval_month_status, :value => "申請中" %>
                  <%= f.hidden_field :report_month, :value => @first_day %>
                  <%= f.collection_select :application_onemonth_superior_name, @superiors, :name, :name, {prompt: "選択してください"}, class: "form-control" %>
                  <%= f.submit "申請送信", class: "btn btn-block btn-primary btn-attendance" %>
                <% end %>
              </li>
            <% end %>
          </ol>
        </td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %>日</td>
        <td colspan="6"><%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="3"></td>
        <td></td>
        <td></td>
      </tr>
    </tfoot>
  </table> 
</div>
<% end %>

<!--モーダルウィンドウ表示-->
<div id="approval-edit-month" class="modal fade" tabindex="10" role="dialog" aria-hidden="true"></div>
<div id="approval-overtime-request" class="modal fade" tabindex="10" role="dialog" aria-hidden="true"></div>
<div id="overtime-request" class="modal fade" tabindex="10" role="dialog" aria-hidden="true"></div>
<div id="approval-report" class="modal fade" tabindex="10" role="dialog" aria-hidden="true"></div>