config/routes.rb
Rails.application.routes.draw do
  
# トップページ
  root 'static_pages#top'
  get  '/signup', to:'users#new'
  get  '/edit-attendance-system', to:'attendances#edit_attendance_system'
  
# ログインのルーティング
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/login', to: 'sessions#destroy'

# 拠点のルーティング
  resources :offices

# ユーザーに紐づける
  resources :users do
    member do
      # ユーザー基本情報
      get   'edit_basic_info'
      patch 'update_basic_info'
      
      # 勤怠情報編集
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'approval_show'
      get   'attendances/approval_log'
    end

    # 勤怠情報編集確認
    get   'approval_edit_month'
    patch 'update_approval_edit_month'

    # 残業申請確認
    get   'approval_overtime_request'
    patch 'update_approval_overtime_request'
    
    # 1ヶ月の申請確認
    get   'approval_one_month'
    patch 'update_approval_one_month'
    
    get   'approval_month_report'
    patch 'update_approval_month_report'
    
    get   'employee_index'
    
    # 勤怠情報に紐付ける
    resources :attendances, only: [:update, :edit] do
      member do
        # 残業申請依頼
        get   'overtime_request'
        patch 'update_overtime_request'
      end
    end
    
    resources :reports, only: :update
    
    # ユーザー情報をCSVからインポート
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates   :worked_on, presence: true
  validates   :note, length: { maximum: 50 }
  
  
  # 出社時間がない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出社。退社時間どちらも存在する場合、出社時間より早い退社時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  # validate :empty_notes_when_editing
  validate :not_selected_supelior
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if (started_at.present? && finished_at.present?) && next_day == "0" # 且つnext_dayが"0"の場合
      errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
    end
  end
  
  def not_selected_supelior
    errors.add(:overtime_application_superior_name,"を選択してください。") if (overtime_finished_at.present? && overtime_note.present?) && overtime_application_superior_name.blank?
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :approval_log]
  before_action :logged_in_user, only: [:update, :edit_ont_month, :import, :update_one_month, :approval_log]
  before_action :set_one_month, only: [:edit_one_month]
  before_action :edit_one_month_approval, only: :edit_approval_page
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直して下さい。"
  
  def edit_attendance_system
  end

# 出社・退社時間の入力
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.started_at.nil?
      @attendance.edit_started_at = @attendance.started_at
      @attendance.log_started_at = @attendance.started_at
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0),
                                        edit_started_at: Time.current.change(sec: 0),
                                        log_started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      @attendance.edit_finished_at = @attendance.finished_at
      @attendance.log_finished_at = @attendance.finished_at
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0),
                                        edit_finished_at: Time.current.change(sec: 0),
                                        log_finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
        @attendance.edit_next_day = @attendance.next_day if @attendance.started_at.present? || @attendance.finished_at
    end
    redirect_to @user
  end
  
  # 勤怠編集画面を表示させる（するときの処理）
  def edit_one_month
    @superiors = User.where(superior: true).where.not(id: @user.id).select(:name)
  end
  
  # 勤怠情報の編集申請（するときの処理）
  def update_one_month
    n = 0
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item| 
        attendance = Attendance.find(id)
        if item[:application_superior_name].present? 
          if item[:edit_started_at].blank?
            flash[:danger] = "出社時間の入力が必要です。"
            redirect_to attendances_edit_one_month_user_url(@user) and return
          elsif item[:edit_finished_at].blank? 
            flash[:danger] = "退社時間の入力が必要です。"
            redirect_to attendances_edit_one_month_user_url(@user) and return
          elsif (item[:edit_next_day] =="0") && (item[:edit_started_at] > item[:edit_finished_at])
            flash[:danger] = "出社時間より早い退社時間はできません。"
            redirect_to attendances_edit_one_month_user_url(@user) and return
          elsif item[:edit_note].blank? 
            flash[:danger] = "備考へ内容を記入してください。"
            redirect_to attendances_edit_one_month_user_url(@user) and return #空の項目はないか
          end
        if attendance.edit_status == "承認"
          item[:edit_status] = "申請中"
          item[:before_started_at] = attendance.started_at
          item[:before_finished_at] = attendance.finished_at
          item[:before_edit_note] = attendance.note
          item[:note] = item[:edit_note]
          item[:before_application_superior_name] = attendance.application_superior_name
          # binding.pry
          attendance.update_attributes!(item)
          n += 1
        elsif attendance.edit_status == "否認"
          item[:edit_status] = "申請中"
          item[:before_started_at] = attendance.started_at
          item[:before_finished_at] = attendance.finished_at
          item[:note] = item[:edit_note]
          attendance.update_attributes!(item)
          n += 1
        else
          item[:edit_status] = "申請中"
          item[:log_started_at] = attendance.started_at if attendance.started_at.blank?
          item[:log_finished_at] = attendance.finished_at if attendance.finished_at.blank?
          item[:before_started_at] = attendance.started_at
          item[:before_finished_at] = attendance.finished_at
          item[:note] = item[:edit_note]
          attendance.update_attributes!(item)
          n += 1
        end
          
        # elsif item[:edit_started_at].present? || item[:edit_finished_at].present? || item[:edit_note].present?
        #   flash[:danger] = "上長の入力が必要です。"
        #   redirect_to attendances_edit_one_month_user_url(@user) and return
        end
      end #do
    end #do
    flash[:success] = "勤務変更を#{n}件申請しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  def overtime_request
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @superiors = User.where(superior: true).where.not(id: @user.id).select(:name)
    
  end
  
  def update_overtime_request #一件のみ保存する
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
        # binding.pry
    # t = Time.current
    # @time_current = t.strftime("%H:%M")
    # @next_day_judge1 = params[:attendance][:overtime_finished_at] < @time_current
    # @next_day_judge2 = format("%.2f",((@user.designated_work_end_time.hour + (@user.designated_work_end_time.min)/60.0))) > params[:attendance][:overtime_finished_at]
    # if @next_day_judge1 == true && @attendance.worked_on == Date.today && params[:attendance][:overtime_next_day] == "0"
    #   flash[:danger] = "翌日になる場合は、翌日にチェックを入れてください。"
    #   redirect_to @user and return
    # elsif @next_day_judge2 == true && @attendance.started_at == nil && @attendance.finished_at == nil && params[:attendance][:overtime_next_day] == "0"
    #   flash[:danger] = "翌日になる場合は、翌日にチェックを入れてください。"
    #   redirect_to @user and return
    # else
      if params[:attendance][:overtime_finished_at].present?
        params[:attendance][:overtime_status] = "申請中" 
        if @attendance.update_attributes!(overtime_params)
          flash[:success] = "残業申請を行いました。"
          redirect_to @user and return
        else
          flash[:danger] = "申請に失敗しました。"
          redirect_to @user and return
        end
      end
    # end
  end
  
  def approval_log
    if params["edit_approval_date(1i)"].present?
      @search_date = Date.new(params["edit_approval_date(1i)"].to_i,params["edit_approval_date(2i)"].to_i,params["edit_approval_date(3i)"].to_i)
      @last_day = @search_date.end_of_month
    end
    @attendances = @user.attendances.where(log_edit_status: "承認", worked_on: @search_date..@last_day).order(:worked_on)
  end
    
  private
    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :next_day, :note, :before_started_at, :before_started_at,
                            :before_edit_note, :edit_started_at, :edit_finished_at, :edit_next_day, :edit_note, :edit_status, 
                            :application_superior, :application_superior_name, :edit_confirmation])[:attendances]
    end
    
    def overtime_params
      params.require(:attendance).permit(:overtime_finished_at, :overtime_next_day,
                            :overtime_note, :overtime_status, 
                            :overtime_application_superior_name)
    end
    
    def approval_one_month_params
      params.require(:attendance).permit(:application_onemonth_superior_name, :one_month_status)
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance) #ボタンのコードを一つにしてボタンに表示されるテキストの条件を決める。
    # 受けとったAttendanceオブジェクトが当日と一致するか評価する
    if Date.current == attendance.worked_on
      return "出勤" if attendance.started_at.nil?
      return "退勤" if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらない場合falseをかえす
    false
  end
  
  # 出社時間と退社時間を受け取り、在社時間を計算して返す。

  def working_times(start, finish, next_day)
    if next_day == "1"
      format("%.2f", (((finish - start) / 60) / 60.0) + 24)
    else
      format("%.2f", (((finish - start) / 60) / 60.0))
    end
  end
  
  # メソッド 名（1,2,3)の順番で引数を呼び出す。引数はカラム名は使わない。
  def overtimes_1(overtimefinish, overtime_next_day)
    if overtime_next_day == "1"
      format("%.2f", ((overtimefinish.hour - @user.designated_work_end_time.hour) + ((overtimefinish.min - @user.designated_work_end_time.min) / 60.0) + 24))
    else
      format("%.2f", ((overtimefinish.hour - @user.designated_work_end_time.hour) + ((overtimefinish.min - @user.designated_work_end_time.min) / 60.0)))
    end
  end
  
  # def overtimes_2(day_start, day_finish, next_day)
  #   @overtime_judge = format("%.2f",((@user.basic_work_time.hour + (@user.basic_work_time.min)/60.0))) #@overtime_judge 基本勤務時間
  #   if day_finish.present? && @overtime_judge.to_f < @str_times.to_f
  #     if next_day == "1"
  #       (@str_times.to_f + 24) - @overtime_judge.to_f
  #     else
  #       @str_times.to_f - @overtime_judge.to_f
  #     end
  #   else
  #     @str_times.to_f - @overtime_judge.to_f
  #   end
  # end
  
  def overtimes_3(day_start, overtime_finish, next_day)
    @overtime_judge = format("%.2f",((@user.basic_work_time.hour + (@user.basic_work_time.min)/60.0)))
    @start_present_overtime_judge = format("%.2f",((day_start.hour + (day_start.min)/60.0)))
    @scheduled_to_end = format("%.2f",((overtime_finish.hour + (overtime_finish.min)/60.0)))
    if day_start.present?
      if next_day == "1"
        (@scheduled_to_end.to_f + 24 ) - @start_present_overtime_judge.to_f - @overtime_judge.to_f
      else
        @scheduled_to_end.to_f - @start_present_overtime_judge.to_f - @overtime_judge.to_f
      end
    end
  end
  
  def overtimes_4(overtime_finish, next_day)
    @design_work_end = format("%.2f",((@user.designated_work_end_time.hour + (@user.designated_work_end_time.min)/60.0))) 
    @scheduled_to_end = format("%.2f",((overtime_finish.hour + (overtime_finish.min)/60.0)))
    if overtime_finish.present?
      if next_day == "1"
        (@scheduled_to_end.to_f + 24 ) - @design_work_end.to_f
      else
        @scheduled_to_end.to_f - @design_work_end.to_f
      end
    end
  end
  
  def format_hour(time) #時間表示の「時間部分」を２桁（００）で表示する。
    format("%02d", time.hour)
  end
  
  def format_min(time) #時間表示び「分部分」を２桁（００）で表示する。
    format("%02d", ((time.min / 15) * 15)) #time.minを15で割り、%02bで自動的に小数点は消え、15を掛け戻すことで15分で丸まる
  end
end

app/views/attendances/_approval_overtime_request.html.erb
<% provide(:title, @user.name) %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
<!--headerにタイトルと、クローズボタン-->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請承認</h1>
    </div>
    
<!--@userのフォーム-->
    <div class="modal-body">
      <%= form_with(model: @user, url: user_update_approval_edit_month_path(@attendances), local: true, method: :patch) do |f| %>
        <% @attendances.each do |id, attendances| %>
          <% user = User.find(id) %>
          <div>
            <h3 class><%= "【#{user.name}からの勤怠変更申請】"%></h3>
            <table class="table table-bordered table-condensed" id="table-attendances">
              <thead>
                <tr>
                  <td>日付</td>
                  <td>曜日</td>
                  <td>終了予定時間</td>
                  <td>指定勤務終了時間</td>
                  <td>時間外時間</td>
                  <td>業務処理内容</td>
                  <td>指示者確認㊞</td>
                  <td>変更</td>
                  <td>勤怠を確認する</td>
                </tr>
              </thead>
              
              <tbody>
                <% attendances.each do |attendance| %>
                  <%= f.fields_for "attendances[]", attendance do |at| %>
                    <%  css_class = 
                        case %w{日 月 火 水 木 金 土}[attendance.worked_on.wday]
                        when '土' then 'text-primary'
                        when '日' then 'text-danger'
                        end
                    %> 
                    <tr>
                      <td><%= l(attendance.worked_on, format: :short) %></td>
                      <td class="<%= css_class %>"><%= $days_of_the_week[attendance.worked_on.wday] %></td>
                      <td><%= attendance.overtime_finished_at if attendance.started_at.present? %></td>
                      <td><%= attendance.started_at.floor_to(15.minutes).min if attendance.started_at.present? %></td>
                      <td><%= attendance.finished_at.hour if attendance.finished_at.present? %></td>
                      <td><%= attendance.finished_at.floor_to(15.minutes).min if attendance.finished_at.present? %></td>
                      
                      <td><%= attendance.edit_started_at.hour if attendance.edit_started_at.present? %></td>
                      <td><%= attendance.edit_started_at.floor_to(15.minutes).min if attendance.edit_started_at.present? %></td>
                      <td><%= attendance.edit_finished_at.hour if attendance.edit_finished_at.present? %></td>
                      <td><%= attendance.edit_finished_at.floor_to(15.minutes).min if attendance.edit_finished_at.present? %></td>
                      
                      <td><%= at.check_box :edit_next_day %></td>
                      <td><%= attendance.note %></td>
                      <td><%= at.select :edit_status, ["なし", "申請中", "承認", "否認"], {include_blank: ""}, class: "form-control" %></td>
                      <td><%= at.check_box :edit_confirmation %></td>
                      <td><%= link_to "確認", approval_show_user_path(id: user.id, date: attendance.worked_on.beginning_of_month), class: "btn btn-primary btn-attendance" %></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
        <div class="center">
          <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_overtime_request.html.erb
<% provide(:title, @user.name) %>
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    
<!--headerにタイトルと、クローズボタン-->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    
    <div class="modal-body">
      <%= form_with(model: @attendance, url: update_overtime_request_user_attendance_path(@user, @attendance), method: :patch) do |f| %>
        <div>
          <table class="table table-bordered table-condensed" id="table-attendances">
            <thead>
              <tr>
                <td>日付</td>
                <td>曜日</td>
                <td>終了予定時間</td>
                <td>翌日</td>
                <td>業務処理内容</td>
                <td>指示者確認㊞</td>
              </tr>
            </thead>
            
            <tbody>
              <%  css_class = 
                  case %w{日 月 火 水 木 金 土}[@attendance.worked_on.wday]
                  when '土' then 'text-primary'
                  when '日' then 'text-danger'
                  end
              %> 
              <tr>
                <td><%= l(@attendance.worked_on, format: :short) %></td>
                <td class="<%= css_class %>"><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
                <td><%= f.time_field :overtime_finished_at, class: "form-control" %></td>
                <td><%= f.check_box :overtime_next_day %></td>
                <td><%= f.select :overtime_note,["作業フォローのため残業します。", "トラブル対応のため残業します。", "納期対応の為、残業します。", "突発対応の為残業します。"], {include_blank: ""}, class: "form-control" %></td>
                <td><%= f.collection_select :overtime_application_superior_name, @superiors, :name, :name, {include_blank: true, selected: nil}, class: "form-control" %></td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="center">
          <%= f.submit "残業申請送信", class: "btn btn-block btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
  
 

app/views/attendances/approval_log.html.erb
<% provide(:title, @user.name) %>

<!--勤怠検索-->
<div>
  <h1>勤怠ログ</h1>
  <form class="form-inline" >
    <%= form_with url: @user, method: :get, local: true do |f| %>
      <%= link_to "リセット", attendances_approval_log_user_path(@user), class: "btn btn-md btn-default" %>
      <%= f.date_select :edit_approval_date, {prompt: Time.now.month,
                                              selected: @search_date,
                                              use_month_numbers: true,
                                              start_year: (Time.now.year),
                                              end_year: (Time.now.year - 3),
                                              start_month: (Time.now.month),
                                              discard_day:true},
                                              {class: 'form-control  bootstrap-date', style: 'display: inline-block;width: auto;'} %>
      <%= f.submit '検索', class: "btn btn-md btn-primary" %>
    <% end %>
  </form>
</div>


<div>
  <table class="table table-bordered table-condensed" id="table-attendances">
    <thead>
      <tr>
        <td>日付</td>
        <td>曜日</td>
        <td>変更前出社時間</td>
        <td>変更前退社時間</td>
        <td>変更後出社時間</td>
        <td>変更後退社時間</td>
        <td>指示者</td>
        <td>承認日️</td>
      </tr>
    </thead>
  
    <tbody>
      <% @attendances.each do |attendance| %>
      
        <%  css_class = 
            case %w{日 月 火 水 木 金 土}[attendance.worked_on.wday]
            when '土' then 'text-primary'
            when '日' then 'text-danger'
            end
        %>      
        <tr>
          <td><%= l(attendance.worked_on) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[attendance.worked_on.wday] %></td>
          <td><%= l(attendance.log_started_at, format: :time) if attendance.log_started_at.present? %></td>
          <td><%= l(attendance.log_finished_at, format: :time) if attendance.log_finished_at.present? %></td>
          <td><%= l(attendance.started_at, format: :time) if attendance.started_at.present? %></td>
          <td><%= l(attendance.finished_at, format: :time) if attendance.finished_at.present? %></td>
          <td><%= attendance.application_superior_name %></td>
          <td><%= l(attendance.edit_approval_date) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/attendances/edit_attendance_system.html.erb
<h1 class>【基本情報修正】</h1>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<!--@userのフォーム-->

<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>

  <div>
  <h1>勤怠編集</h1>
    <table class="table table-bordered table-condensed" id="table-attendances">
      <thead>
        <tr>
          <td>日付</td>
          <td>曜日</td>
          <td>出社</td>
          <td>退社</td>
          <td>翌日</td>
          <td>在社時間</td>
          <td>備考</td>
          <td>指示者確認㊞️</td>
        </tr>
      </thead>
      
      <tbody>
<!--@attendancesをdayとして取り出して繰り返す-->
        <% @attendances.each do |day| %>
<!--attendanceのフォーム-->
          <%= f.fields_for "attendances[]", day do |attendance| %>
          <%  css_class = 
              case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
              when '土' then 'text-primary'
              when '日' then 'text-danger'
              end
          %>      
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if !current_user.admin? && (Date.current < day.worked_on) %>
                <td><%= attendance.time_field :edit_started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :edit_finished_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.check_box :edit_next_day, {disabled: true} %></td>
                <td>
                  <% if day.started_at.present? && day.finished_at.present? %>
            <!--ヘルパーのworking_timesに引数next_dayを追加(workingtimesはst時間、fn時間、nxのcbを参照する)-->
                    <%= @str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.next_day) %>
                    <% @total_working_times = @total_working_times.to_f + @str_times.to_f %>
                  <% end %>
                </td>
                <td><%= attendance.text_field :edit_note, readonly:true, class: "form-control" %></td>
                <td><%= attendance.collection_select :application_superior_name, @superiors, :name, :name, {include_blank: true, selected: "" }, disabled: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :edit_started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :edit_finished_at, class: "form-control" %></td> 
                <td><%= attendance.check_box :edit_next_day %></td>
                <td>
                  <% if day.started_at.present? && day.finished_at.present? %>
            <!--ヘルパーのworking_timesに引数next_dayを追加(workingtimesはst時間、fn時間、nxのcbを参照する)-->
                    <%= @str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.next_day) %>
                    <% @total_working_times = @total_working_times.to_f + @str_times.to_f %>
                  <% end %>
                </td>
                <td><%= attendance.text_field :edit_note, placeholder: "入力必須", class: "form-control" %></td>
                <td><%= attendance.collection_select :application_superior_name, @superiors, :name, :name, {include_blank: true, selected: "" }, class: "form-control" %></td>
                    <%= attendance.hidden_field :application_superior, :value => @user.id %>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/overtime_request.js.erb
<!--１行目で_approval_edit_monthをレンダリングする-->
$("#overtime-request").html("<%= escape_javascript(render 'overtime_request') %>");
<!--２行目でmモーダルウインドウとして表示している。-->
$("#overtime-request").modal("show");