config/routes.rb
Rails.application.routes.draw do
  
# トップページ
  root 'static_pages#top'
  get  '/signup', to:'users#new'
  get  '/edit-attendance-system', to:'attendances#edit_attendance_system'
  
# ログインのルーティング
  get     '/login', to: 'sessions#new'
  post    '/login', to: 'sessions#create'
  delete  '/login', to: 'sessions#destroy'

# 拠点のルーティング
  resources :offices

# ユーザーに紐づける
  resources :users do
    member do
      # ユーザー基本情報
      get   'edit_basic_info'
      patch 'update_basic_info'
      
      # 勤怠情報編集
      get   'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get   'approval_show'
      get   'attendances/approval_log'
    end

    # 勤怠情報編集確認
    get   'approval_edit_month'
    patch 'update_approval_edit_month'

    # 残業申請確認
    get   'approval_overtime_request'
    patch 'update_approval_overtime_request'
    
    # 1ヶ月の申請確認
    get   'approval_one_month'
    patch 'update_approval_one_month'
    
    get   'approval_month_report'
    patch 'update_approval_month_report'
    
    get   'employee_index'
    
    # 勤怠情報に紐付ける
    resources :attendances, only: [:update, :edit] do
      member do
        # 残業申請依頼
        get   'overtime_request'
        patch 'update_overtime_request'
      end
    end
    
    resources :reports, only: :update
    
    # ユーザー情報をCSVからインポート
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance A", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
        <% unless current_user.admin? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠ページ", current_user %></li>
              <li><%= link_to "ユーザー情報編集", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", login_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li><%= link_to "出勤社員一覧", user_employee_index_path(current_user.id) %></li>
          <li><%= link_to "拠点の編集", offices_path %></li>
          <li><%= link_to "基本情報の修正", edit_attendance_system_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <% if current_user.admin? %>
              <ul class="dropdown-menu">
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", login_path, method: :delete %>
                </li>
              </ul>
            <% else %>
              <ul class="dropdown-menu">
                <li><%= link_to "勤怠ページ", current_user %></li>
                <li><%= link_to "ユーザー情報編集", edit_user_path(current_user) %></li>
                <li><%= link_to "拠点登録", new_office_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "ログアウト", login_path, method: :delete %>
                </li>
              </ul>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <li><%= link_to "ログイン", login_path %></li>
      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>